# Generated by Django 3.2.6 on 2022-04-17 20:42

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_auto_20220412_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', help_text='Выберите цвет тега', image_field=None, max_length=8, samples=None, unique=True, verbose_name='Цвет'),
        ),
    ]
