# Generated by Django 3.2.6 on 2022-04-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_ingredientsinrecipe_unique_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='backend_media/recipes/', verbose_name='Изображение'),
        ),
    ]
